# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtH6vcfc0jk8LkcJJgzZTJ00ZQ97BLz-
"""
import streamlit as st
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score

show_research = st.toggle("Show Research & Model Validation Panel")

if show_research:
    cv_scores = cross_val_score(classifier, X_class, y_class, cv=5)
    st.write("5-Fold Cross Validation Accuracy:", round(cv_scores.mean(), 3))

st.set_page_config(page_title="PREDICT+", layout="centered")

# -----------------------------
# Train model once (cached)
# -----------------------------
@st.cache_resource
def train_model():
    np.random.seed(42)
    n = 500

    sleep = np.random.uniform(4, 10, n)
    hydration = np.random.uniform(1, 3.5, n)
    stress = np.random.uniform(0, 10, n)
    activity = np.random.uniform(0, 90, n)
    movement = np.random.uniform(5, 40, n)
    gest_age = np.random.uniform(20, 40, n)
    bmi = np.random.uniform(18, 35, n)

    sleep_n = sleep / 12
    hydration_n = hydration / 4
    stress_n = 1 - (stress / 10)
    activity_n = activity / 120
    movement_n = movement / 50
    ga_n = (gest_age - 20) / 20
    bmi_n = 1 - abs(bmi - 25) / 15

    fcs = (
        0.20 * sleep_n +
        0.15 * hydration_n +
        0.20 * stress_n +
        0.15 * activity_n +
        0.15 * movement_n +
        0.10 * ga_n +
        0.05 * bmi_n
    )

    df = pd.DataFrame({
        "sleep": sleep,
        "hydration": hydration,
        "stress": stress,
        "activity": activity,
        "movement": movement,
        "gest_age": gest_age,
        "bmi": bmi,
        "fcs": fcs
    })

    df["risk"] = pd.qcut(df["fcs"], q=3, labels=["High", "Moderate", "Low"])

    X = df[["sleep","hydration","stress","activity","movement","gest_age","bmi"]]
    y = df["risk"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)

    return model

model = train_model()

# -----------------------------
# Interface
# -----------------------------
st.title("PREDICT+")
st.subheader("Maternal–Fetal Wellness Computational Prototype")

sleep = st.slider("Sleep (hours)", 0.0, 12.0, 7.0)
hydration = st.slider("Hydration (liters/day)", 0.0, 5.0, 2.5)
stress = st.slider("Stress Level (0-10)", 0, 10, 5)
activity = st.slider("Physical Activity (minutes)", 0, 120, 30)
movement = st.slider("Fetal Movement (kicks/day)", 0, 50, 20)
gestation = st.slider("Gestational Age (weeks)", 1, 40, 20)
bmi = st.slider("BMI", 15.0, 40.0, 25.0)

# Normalize inputs (0–1 scaling)

sleep_n = sleep / 12
hydration_n = hydration / 5
stress_n = 1 - (stress / 10)      # higher stress = lower comfort
activity_n = activity / 120
movement_n = movement / 50
gestation_n = gestation / 40
bmi_n = 1 - abs(bmi - 22) / 20    # ideal BMI around 22

# Weighted FCS formula
FCS = (
    0.20 * sleep_n +
    0.15 * hydration_n +
    0.20 * stress_n +
    0.15 * activity_n +
    0.15 * movement_n +
    0.05 * gestation_n +
    0.10 * bmi_n
)



st.subheader("Fetal Comfort Score")

if FCS >= 0.75:
    st.success(f"🟢 Optimal Comfort — Score: {FCS:.2f}")
elif FCS >= 0.50:
    st.warning(f"🟡 Moderate Comfort — Score: {FCS:.2f}")
else:
    st.error(f"🔴 Suboptimal Comfort — Score: {FCS:.2f}")



import pandas as pd

contributions = {
    "Sleep": 0.20 * sleep_n,
    "Hydration": 0.15 * hydration_n,
    "Stress": 0.20 * stress_n,
    "Activity": 0.15 * activity_n,
    "Movement": 0.15 * movement_n,
    "Gestation": 0.05 * gestation_n,
    "BMI": 0.10 * bmi_n
}

df = pd.DataFrame(list(contributions.items()), columns=["Factor", "Contribution"])

st.bar_chart(df.set_index("Factor"))



if st.button("Run Sensitivity Analysis"):
    sensitivity = {
        k: round(v / FCS * 100, 2) for k, v in contributions.items()
    }
    st.write("Relative Impact (%)")
    st.write(sensitivity)


import numpy as np

predicted_FCS = FCS + np.random.normal(0, 0.03)

st.subheader("Next-Day Predicted Comfort")
st.write(f"Predicted Score: {predicted_FCS:.2f}")


with st.expander("Model Design Explanation"):
    st.write("""
    The Fetal Comfort Score is a weighted, normalized composite index
    derived from literature-supported maternal wellness factors.
    Each variable was scaled to 0–1 and assigned weights based on
    relative physiological impact reported in published studies.
    """)


import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

@st.cache_data
def generate_dataset(n=1000):
    data = pd.DataFrame({
        "sleep": np.random.uniform(4, 10, n),
        "hydration": np.random.uniform(1, 4, n),
        "stress": np.random.uniform(0, 10, n),
        "activity": np.random.uniform(0, 90, n),
        "movement": np.random.uniform(5, 40, n),
        "gestation": np.random.uniform(5, 40, n),
        "bmi": np.random.uniform(18, 35, n)
    })

    # Hidden physiological relationship (ground truth)
    data["FCS_true"] = (
        0.22*(data["sleep"]/10) +
        0.15*(data["hydration"]/4) +
        0.20*(1-data["stress"]/10) +
        0.13*(data["activity"]/90) +
        0.15*(data["movement"]/40) +
        0.05*(data["gestation"]/40) +
        0.10*(1-abs(data["bmi"]-22)/15)
    )

    return data



data = generate_dataset()

X = data.drop("FCS_true", axis=1)
y = data["FCS_true"]

model = LinearRegression()
model.fit(X, y)


input_df = pd.DataFrame([{
    "sleep": sleep,
    "hydration": hydration,
    "stress": stress,
    "activity": activity,
    "movement": movement,
    "gestation": gestation,
    "bmi": bmi
}])

FCS = model.predict(input_df)[0]


coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Learned Weight": model.coef_
})

st.subheader("Model-Learned Feature Importance")
st.bar_chart(coef_df.set_index("Feature"))


from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression

data = generate_dataset()

X = data.drop("FCS_true", axis=1)
y = data["FCS_true"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

# Validation metrics
y_pred = model.predict(X_test)

MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)



st.subheader("Model Validation Metrics")

col1, col2 = st.columns(2)

col1.metric("Mean Absolute Error (MAE)", f"{MAE:.4f}")
col2.metric("R² Score", f"{R2:.4f}")



with st.expander("Model Validation Explanation"):
    st.write("""
    The dataset was split into 80% training and 20% testing data.
    The regression model was trained on the training set and evaluated
    on unseen test data.

    • MAE (Mean Absolute Error) measures average prediction error.
    • R² measures how well the model explains variance in fetal comfort.

    High R² and low MAE indicate strong predictive performance.
    """)


from sklearn.linear_model import LogisticRegression

# Create risk categories
data["Risk_Category"] = pd.cut(
    data["FCS_true"],
    bins=[0, 0.5, 0.75, 1],
    labels=["High Risk", "Moderate Risk", "Low Risk"]
)

X_class = data.drop(["FCS_true", "Risk_Category"], axis=1)
y_class = data["Risk_Category"]

Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_class, y_class, test_size=0.2, random_state=42
)

classifier = LogisticRegression(max_iter=1000)
classifier.fit(Xc_train, yc_train)

classification_accuracy = classifier.score(Xc_test, yc_test)


st.subheader("Risk Classification Model")

st.metric("Classification Accuracy", f"{classification_accuracy:.3f}")

risk_prediction = classifier.predict(input_df)[0]

st.subheader("Predicted Risk Category")
st.write(risk_prediction)

# ------------------------------
# Research Panel (Hidden Toggle)
# ------------------------------

show_research = st.toggle("Show Research & Model Validation Panel")

if show_research:
    from sklearn.model_selection import cross_val_score
    
    cv_scores = cross_val_score(classifier, X_class, y_class, cv=5)
    
    st.subheader("Cross Validation")
    st.write("5-Fold Cross Validation Accuracy:", round(cv_scores.mean(), 3))
