# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtH6vcfc0jk8LkcJJgzZTJ00ZQ97BLz-
"""

import streamlit as st
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

st.set_page_config(page_title="PREDICT+", layout="centered")

# -----------------------------
# Train model once (cached)
# -----------------------------
@st.cache_resource
def train_model():
    np.random.seed(42)
    n = 500

    sleep = np.random.uniform(4, 10, n)
    hydration = np.random.uniform(1, 3.5, n)
    stress = np.random.uniform(0, 10, n)
    activity = np.random.uniform(0, 90, n)
    movement = np.random.uniform(5, 40, n)
    gest_age = np.random.uniform(20, 40, n)
    bmi = np.random.uniform(18, 35, n)

    sleep_n = sleep / 12
    hydration_n = hydration / 4
    stress_n = 1 - (stress / 10)
    activity_n = activity / 120
    movement_n = movement / 50
    ga_n = (gest_age - 20) / 20
    bmi_n = 1 - abs(bmi - 25) / 15

    fcs = (
        0.20 * sleep_n +
        0.15 * hydration_n +
        0.20 * stress_n +
        0.15 * activity_n +
        0.15 * movement_n +
        0.10 * ga_n +
        0.05 * bmi_n
    )

    df = pd.DataFrame({
        "sleep": sleep,
        "hydration": hydration,
        "stress": stress,
        "activity": activity,
        "movement": movement,
        "gest_age": gest_age,
        "bmi": bmi,
        "fcs": fcs
    })

    df["risk"] = pd.qcut(df["fcs"], q=3, labels=["High", "Moderate", "Low"])

    X = df[["sleep","hydration","stress","activity","movement","gest_age","bmi"]]
    y = df["risk"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)

    return model

model = train_model()

# -----------------------------
# Interface
# -----------------------------
st.title("PREDICT+")
st.subheader("Maternal–Fetal Wellness Computational Prototype")

sleep = st.slider("Sleep (hours)", 0.0, 12.0, 7.0)
hydration