# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtH6vcfc0jk8LkcJJgzZTJ00ZQ97BLz-
"""

import streamlit as st
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

st.set_page_config(page_title="PREDICT+", layout="centered")

# -----------------------------
# Train model once (cached)
# -----------------------------
@st.cache_resource
def train_model():
    np.random.seed(42)
    n = 500

    sleep = np.random.uniform(4, 10, n)
    hydration = np.random.uniform(1, 3.5, n)
    stress = np.random.uniform(0, 10, n)
    activity = np.random.uniform(0, 90, n)
    movement = np.random.uniform(5, 40, n)
    gest_age = np.random.uniform(20, 40, n)
    bmi = np.random.uniform(18, 35, n)

    sleep_n = sleep / 12
    hydration_n = hydration / 4
    stress_n = 1 - (stress / 10)
    activity_n = activity / 120
    movement_n = movement / 50
    ga_n = (gest_age - 20) / 20
    bmi_n = 1 - abs(bmi - 25) / 15

    fcs = (
        0.20 * sleep_n +
        0.15 * hydration_n +
        0.20 * stress_n +
        0.15 * activity_n +
        0.15 * movement_n +
        0.10 * ga_n +
        0.05 * bmi_n
    )

    df = pd.DataFrame({
        "sleep": sleep,
        "hydration": hydration,
        "stress": stress,
        "activity": activity,
        "movement": movement,
        "gest_age": gest_age,
        "bmi": bmi,
        "fcs": fcs
    })

    df["risk"] = pd.qcut(df["fcs"], q=3, labels=["High", "Moderate", "Low"])

    X = df[["sleep","hydration","stress","activity","movement","gest_age","bmi"]]
    y = df["risk"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)

    return model

model = train_model()

# -----------------------------
# Interface
# -----------------------------
st.title("PREDICT+")
st.subheader("Maternal–Fetal Wellness Computational Prototype")

sleep = st.slider("Sleep (hours)", 0.0, 12.0, 7.0)
hydration = st.slider("Hydration (liters/day)", 0.0, 5.0, 2.5)
stress = st.slider("Stress Level (0-10)", 0, 10, 5)
activity = st.slider("Physical Activity (minutes)", 0, 120, 30)
movement = st.slider("Fetal Movement (kicks/day)", 0, 50, 20)
gestation = st.slider("Gestational Age (weeks)", 1, 40, 20)
bmi = st.slider("BMI", 15.0, 40.0, 25.0)

# Normalize inputs (0–1 scaling)

sleep_n = sleep / 12
hydration_n = hydration / 5
stress_n = 1 - (stress / 10)      # higher stress = lower comfort
activity_n = activity / 120
movement_n = movement / 50
gestation_n = gestation / 40
bmi_n = 1 - abs(bmi - 22) / 20    # ideal BMI around 22

# Weighted FCS formula
FCS = (
    0.20 * sleep_n +
    0.15 * hydration_n +
    0.20 * stress_n +
    0.15 * activity_n +
    0.15 * movement_n +
    0.05 * gestation_n +
    0.10 * bmi_n
)



st.subheader("Fetal Comfort Score")

if FCS >= 0.75:
    st.success(f"🟢 Optimal Comfort — Score: {FCS:.2f}")
elif FCS >= 0.50:
    st.warning(f"🟡 Moderate Comfort — Score: {FCS:.2f}")
else:
    st.error(f"🔴 Suboptimal Comfort — Score: {FCS:.2f}")



import pandas as pd

contributions = {
    "Sleep": 0.20 * sleep_n,
    "Hydration": 0.15 * hydration_n,
    "Stress": 0.20 * stress_n,
    "Activity": 0.15 * activity_n,
    "Movement": 0.15 * movement_n,
    "Gestation": 0.05 * gestation_n,
    "BMI": 0.10 * bmi_n
}

df = pd.DataFrame(list(contributions.items()), columns=["Factor", "Contribution"])

st.bar_chart(df.set_index("Factor"))





if st.button("Run Sensitivity Analysis"):
    sensitivity = {
        k: round(v / FCS * 100, 2) for k, v in contributions.items()
    }
    st.write("Relative Impact (%)")
    st.write(sensitivity)




import numpy as np

predicted_FCS = FCS + np.random.normal(0, 0.03)

st.subheader("Next-Day Predicted Comfort")
st.write(f"Predicted Score: {predicted_FCS:.2f}")




with st.expander("Model Design Explanation"):
    st.write("""
    The Fetal Comfort Score is a weighted, normalized composite index
    derived from literature-supported maternal wellness factors.
    Each variable was scaled to 0–1 and assigned weights based on
    relative physiological impact reported in published studies.
    """)
