# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SuTlJHcd3QxzUjqnfl09oRE0Iiny7Cx
"""

streamlit
numpy
pandas
scikit-learn